# -*- coding: utf-8 -*-
"""Revised_DynamicSWARM_CaliforniaHouse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16J4ALT3nojs5lIVHEcSs6U1VqjNoDGUF
"""

import torch
import numpy as np
import pandas as pd
from torchvision import datasets, transforms
import sklearn
from torch.utils.data import DataLoader, random_split, ConcatDataset, Subset, TensorDataset
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import os
from google.colab import drive
import concurrent.futures
import time
import random
import csv
import copy

# Mount Google Drive for persistent storage
drive.mount('/content/drive')

# === Configuration ===
NUM_CLIENTS = 32             # ↑ from 4  (tens of nodes)
NUM_GLOBAL_ROUNDS = 15       # ↑ from 5  (many more rounds)
NUM_LOCAL_EPOCHS = 5         # ↓ to keep total compute manageable at scale
CLIENT_FRACTION = 0.25       # fraction of clients participating each round (a la FedAvg C)
BATCH_SIZE = 128             # ↑ batch for tabular to speed up
LEARNING_RATE = 5e-4
DIRICHLET_ALPHA = 0.5
NUM_BINS = 10

# Optional realism knobs
ASYNC_STALENESS_PROB = 0.0   # set to 0.2 to simulate 20% staleness
STALENESS_GAMMA = 0.9        # weight decay per round of staleness

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

def load_data(normalize=True, seed=42):
    """
    Load and preprocess the California Housing dataset for regression.
    Mimics the MNIST loader structure but outputs torch tensors instead of images.
    """
    from sklearn.datasets import fetch_california_housing

    # Load dataset
    data = fetch_california_housing()
    X = data.data.astype(np.float32)
    y = data.target.astype(np.float32).reshape(-1, 1)

    # Normalize features (optional)
    if normalize:
        X = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-8)

    # Split into train / validation / test sets
    n = X.shape[0]
    rng = np.random.RandomState(seed)
    idx = rng.permutation(n)
    n_train = int(0.8 * n)
    n_val = int(0.1 * n)

    train_idx = idx[:n_train]
    val_idx = idx[n_train:n_train + n_val]
    test_idx = idx[n_train + n_val:]

    X_train, y_train = X[train_idx], y[train_idx]
    X_val, y_val = X[val_idx], y[val_idx]
    X_test, y_test = X[test_idx], y[test_idx]

    # Convert to tensors
    X_train = torch.tensor(X_train)
    y_train = torch.tensor(y_train)
    X_val = torch.tensor(X_val)
    y_val = torch.tensor(y_val)
    X_test = torch.tensor(X_test)
    y_test = torch.tensor(y_test)

    print("California Housing data has been loaded and split.")
    return (X_train, y_train), (X_val, y_val), (X_test, y_test)

def split_data_nodes(dataset, num_nodes, alpha=0.5, bins=10, seed=42):
    """
    Non-IID partitioning for regression:
    - Assumes `dataset` is a TensorDataset where the 2nd tensor is the continuous target (shape [N,1] or [N]).
    - Discretizes targets into `bins` bins, then applies a Dirichlet(alpha) split per bin across clients.
    - Returns list of Subset(dataset, indices) per client + original dataset + size weightings.
    """
    import numpy as np
    import torch
    from torch.utils.data import Subset

    assert hasattr(dataset, "tensors") and len(dataset.tensors) >= 2, \
        "Expected a TensorDataset with features and targets in dataset.tensors"

    # Extract continuous targets and bin them to create label-like groups
    y = dataset.tensors[1].detach().cpu().numpy().reshape(-1)
    # rng = np.random.RandomState(seed)
    rng = np.random.default_rng()

    # Build bin ids over the continuous target
    edges = np.linspace(y.min(), y.max(), bins + 1)
    bin_ids = np.digitize(y, edges) - 1
    bin_ids = np.clip(bin_ids, 0, bins - 1)

    # Dirichlet split per bin
    client_indices = [[] for _ in range(num_nodes)]
    for c in range(bins):
        idx_c = np.where(bin_ids == c)[0]
        if idx_c.size == 0:
            continue
        rng.shuffle(idx_c)
        props = rng.dirichlet([alpha] * num_nodes)
        # turn proportions into index boundaries
        cuts = (np.cumsum(props) * len(idx_c)).astype(int)[:-1]
        parts = np.split(idx_c, cuts)
        for i, part in enumerate(parts):
            client_indices[i].extend(part.tolist())

    # Shuffle within each client split for good measure
    for lst in client_indices:
        rng.shuffle(lst)

    # Build Subset objects per client
    dataset_splits = [Subset(dataset, inds) for inds in client_indices]

    # Compute weightings for aggregators that use client size
    total = sum(len(s) for s in dataset_splits)
    weightings = [len(s) / total if total > 0 else 0.0 for s in dataset_splits]

    # Logging
    print(f"Data has been split into {num_nodes} clients (Dirichlet alpha={alpha}, bins={bins}, seed={seed})")
    for i, subset in enumerate(dataset_splits):
        print(f"  Size of client {i+1}: {len(subset)}")

    return dataset_splits, dataset, weightings

def create_data_loaders(subset, batch_size=BATCH_SIZE, num_workers=2):
    val_size = int(0.2 * len(subset))
    train_size = len(subset) - val_size
    train_subset, val_subset = torch.utils.data.random_split(subset, [train_size, val_size])

    train_loader = torch.utils.data.DataLoader(train_subset, batch_size=batch_size, shuffle=True,  num_workers=num_workers)
    val_loader   = torch.utils.data.DataLoader(val_subset,   batch_size=batch_size, shuffle=False, num_workers=num_workers)

    print(f"Data loaders created: {train_size} train, {val_size} val.")
    return train_loader, val_loader

# 3. Define the Neural Network Model for Regression
class SimpleNN(nn.Module):
    def __init__(self, input_dim=8, hidden_dim=128):
        """
        Simple 2-layer fully connected network for regression.
        Default input_dim=8 (California Housing features).
        """
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)   # input -> hidden
        self.fc2 = nn.Linear(hidden_dim, 1)           # hidden -> single output value

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x                                      # shape [batch, 1]

    def copy(self):
        # Create a new instance and copy parameters (keeps same interface)
        new_model = SimpleNN(input_dim=self.fc1.in_features,
                             hidden_dim=self.fc1.out_features)
        new_model.load_state_dict(self.state_dict())
        return new_model

def create_final_data_test_loader(test_dataset):
    """
    Create a DataLoader for the final test dataset (regression).
    """
    test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=64, shuffle=False)
    print(f"Final test DataLoader created with {len(test_dataset)} samples.")
    return test_loader

def model_parameters_to_string(model, limit=3):
    """
    Convert model parameters to a readable string for inspection.
    Prints up to `limit` elements per parameter tensor for brevity.
    """
    params_str = "Model Parameters:\n"
    for name, param in model.named_parameters():
        params_str += f"Name: {name}, Shape: {tuple(param.shape)}\n"
        flat = param.data.flatten()
        shown = flat[:limit].tolist()
        params_str += f"Sample values: {shown}"
        if flat.numel() > limit:
            params_str += " ...\n"
        else:
            params_str += "\n"
        params_str += "-" * 50 + "\n"
    return params_str

class Node:
    def __init__(self, node_id, train_loader: DataLoader, test_loader: DataLoader, weighting, aggregation_methodology):
        """
        Node for Regression (California Housing).
        Mirrors original structure but replaces classification metrics with regression ones.
        """
        self.__train_loader = train_loader
        self.test_loader = test_loader
        self.node_id = node_id
        self.global_parameters = []

        # Model, loss, optimizer
        self.model = SimpleNN(input_dim=8)   # 8 features in California Housing
        self.criterion = nn.MSELoss()
        self.optimizer = optim.Adam(self.model.parameters(), lr=0.001)

        # Metrics & state
        self.weighting = weighting
        self.aggregation_methodology = aggregation_methodology
        self.balance_score = self.get_balance_score()
        self.current_epoch = 1

        # Regression metrics tracking
        self.rmse_scores = []
        self.mae_scores = []
        self.r2_scores = []
        self.current_rmse = None

    # -----------------------------
    # Core utilities
    # -----------------------------
    def update_epoch(self):
        self.current_epoch += 1

    def set_aggregation_methodology(self, methodology):
        self.aggregation_methodology = methodology

    def get_model(self):
        return self.model

    # -----------------------------
    # Balance & weighting
    # -----------------------------
    def get_balance_score(self):
        """
        Compute a balance score for regression based on how evenly
        distributed the target values are in this node's data.
        """
        all_targets = []
        for _, y in self.__train_loader:
            all_targets.extend(y.numpy().flatten())

        if len(all_targets) == 0:
            return 0.0

        hist, _ = np.histogram(all_targets, bins=10, density=True)
        hist = hist / np.sum(hist)
        score = 1 - np.std(hist)
        return float(score)

    # -----------------------------
    # Model broadcast & gather
    # -----------------------------
    def broadcast_parameters(self):
        """
        Broadcast packet: [balance_score, weighting, current_rmse, model params...]
        """
        params = [self.balance_score, self.weighting, self.current_rmse or 0.0]
        for p in self.model.parameters():
            params.append(p.clone())
        return params

    def gather_parameters(self, params):
        print(f"Gathered Parameters for Node {self.node_id}")
        self.global_parameters.append(params)
        print(f"Total gathered: {len(self.global_parameters)} packets")

    # -----------------------------
    # Aggregation (size / balance)
    # -----------------------------
    def size_average_parameters(self):
        if not self.global_parameters:
            raise RuntimeError("No gathered parameters to average.")

        params_copy = [pkt[:] for pkt in self.global_parameters]
        weightings = [p[1] for p in params_copy]

        template_tensors = params_copy[0][3:]
        averaged = [torch.zeros_like(t) for t in template_tensors]
        total_weight = sum(weightings)

        for pkt, w in zip(params_copy, weightings):
            for i, t in enumerate(pkt[3:]):
                averaged[i] += t * w

        if total_weight > 0:
            averaged = [t / total_weight for t in averaged]
        return averaged

    def balance_average_parameters(self):
        if not self.global_parameters:
            raise RuntimeError("No gathered parameters to average.")

        params_copy = [pkt[:] for pkt in self.global_parameters]
        balance_scores = [p[0] for p in params_copy]

        template_tensors = params_copy[0][3:]
        averaged = [torch.zeros_like(t) for t in template_tensors]
        total_balance = sum(balance_scores)

        for pkt, b in zip(params_copy, balance_scores):
            for i, t in enumerate(pkt[3:]):
                averaged[i] += t * b

        if total_balance > 0:
            averaged = [t / total_balance for t in averaged]
        return averaged

    # -----------------------------
    # Aggregation testing & selection
    # -----------------------------
    def test_aggregation(self):
        """
        Compare size vs balance aggregation by evaluating RMSE
        on this node's validation set. Return the better one (lower RMSE).
        """
        if not self.global_parameters:
            return self.aggregation_methodology or "balance_average"

        size_model = copy.deepcopy(self.model)
        bal_model = copy.deepcopy(self.model)

        size_params = self.size_average_parameters()
        bal_params = self.balance_average_parameters()

        size_model.load_state_dict(dict(zip(size_model.state_dict().keys(), size_params)))
        bal_model.load_state_dict(dict(zip(bal_model.state_dict().keys(), bal_params)))

        size_rmse, _, _ = evaluate(size_model, self.test_loader)
        bal_rmse, _, _ = evaluate(bal_model, self.test_loader)

        print(f"Node {self.node_id} | Size RMSE={size_rmse:.4f}, Balance RMSE={bal_rmse:.4f}")
        return "size" if size_rmse < bal_rmse else "balance"

    def aggregate_parameters(self):
        """
        Apply the currently chosen aggregation strategy to update this node's model.
        """
        if self.aggregation_methodology == "size_average":
            averaged_params = self.size_average_parameters()
        elif self.aggregation_methodology == "balance_average":
            averaged_params = self.balance_average_parameters()
        else:
            raise ValueError(f"Invalid aggregation methodology: {self.aggregation_methodology}")

        print(f"Node {self.node_id}: applying {self.aggregation_methodology}")
        self.set_parameters(averaged_params)
        self.global_parameters = []

    def set_parameters(self, parameters):
        new_state = dict(zip(self.model.state_dict().keys(), parameters))
        self.model.load_state_dict(new_state)
        print(f"Set parameters for node {self.node_id}")

    # -----------------------------
    # Training & evaluation
    # -----------------------------
    def train(self):
        self.model.train()
        for epoch in range(NUM_LOCAL_EPOCHS):
            total_loss = 0.0
            for X, y in self.__train_loader:
                self.optimizer.zero_grad()
                preds = self.model(X)
                loss = self.criterion(preds, y)
                loss.backward()
                self.optimizer.step()
                total_loss += loss.item()
            print(f"Node {self.node_id} | Epoch {epoch+1}/{NUM_LOCAL_EPOCHS} | Loss: {total_loss/len(self.__train_loader):.4f}")

    def evaluate(self):
        self.model.eval()
        preds, actuals = [], []

        with torch.no_grad():
            for X, y in self.test_loader:
                out = self.model(X)
                preds.extend(out.cpu().numpy().flatten())
                actuals.extend(y.cpu().numpy().flatten())

        preds = np.array(preds)
        actuals = np.array(actuals)
        mse = np.mean((preds - actuals) ** 2)
        mae = np.mean(np.abs(preds - actuals))
        rmse = np.sqrt(mse)
        r2 = 1 - np.sum((preds - actuals) ** 2) / np.sum((actuals - np.mean(actuals)) ** 2)

        self.rmse_scores.append(rmse)
        self.mae_scores.append(mae)
        self.r2_scores.append(r2)
        self.current_rmse = rmse

        print(f"Node {self.node_id} | RMSE: {rmse:.3f}, MAE: {mae:.3f}, R2: {r2:.3f}")
        return rmse, mae, r2

def train_and_communicate(node, nodes):
    # Train the node
    node.train()

    metrics = node.evaluate()
    print("Metrics for Node " + str(node.get_node_id()) + " : " + str(metrics))
    # Send parameters to all other nodes
    for other_node in nodes:
      print("NODE " + str(node.get_node_id()) + "  HAS BROADCASTED ")

      other_node.gather_parameters(node.broadcast_parameters())

def dynamic_aggregation(nodes):
    """
    Dynamically choose between size_average and balance_average
    based on which gives lower RMSE on each node's test set.
    """
    decisions = []
    for node in nodes:
        # Each node’s test_aggregation now returns which aggregation
        # gives LOWER RMSE rather than higher accuracy.
        decisions.append(node.test_aggregation())

    size_votes = decisions.count("size")
    balance_votes = decisions.count("balance")

    if size_votes > balance_votes:
        for node in nodes:
            node.set_aggregation_methodology("size_average")
        decision = "size"
    elif size_votes < balance_votes:
        for node in nodes:
            node.set_aggregation_methodology("balance_average")
        decision = "balance"
    else:
        for node in nodes:
            node.set_aggregation_methodology("balance_average")
        decision = "balance"

    print(f"Dynamic aggregation selected: {decision}")
    return decision

def evaluate(model, test_loader):
    """
    Evaluate regression model on test data.
    Returns: RMSE, MAE, R2
    """
    model.eval()  # evaluation mode

    all_targets = []
    all_predictions = []

    with torch.no_grad():
        for features, targets in test_loader:
            outputs = model(features)
            all_targets.extend(targets.cpu().numpy().flatten())
            all_predictions.extend(outputs.cpu().numpy().flatten())

    all_targets = np.array(all_targets)
    all_predictions = np.array(all_predictions)

    # Regression metrics
    mse = np.mean((all_predictions - all_targets) ** 2)
    mae = np.mean(np.abs(all_predictions - all_targets))
    rmse = np.sqrt(mse)
    r2 = 1 - np.sum((all_predictions - all_targets) ** 2) / np.sum((all_targets - np.mean(all_targets)) ** 2)

    return rmse, mae, r2

# Function to write regression metrics to a CSV file
def write_metrics_to_csv(filename, metrics_list):
    """
    metrics_list = [aggregation_method, RMSE, MAE, R2]
    """
    file_exists = os.path.isfile(filename)

    with open(filename, mode='a', newline='') as file:
        writer = csv.writer(file)

        # Write the header only if creating a new file
        if not file_exists:
            writer.writerow(['Aggregation Method', 'RMSE', 'MAE', 'R2'])

        # Append the metrics
        writer.writerow(metrics_list)

    print(f"Regression metrics written to {filename}")

# === Runs & CSV outputs ===
NUM_RUNS = 30
AGG_CSV = "/content/drive/My Drive/Swarm_Learning/dynamic_regression4.csv"
OVERHEAD_CSV = "/content/drive/My Drive/Swarm_Learning/dynamic_regression_overhead4.csv"

# ensure CSV headers exist
if not os.path.isfile(AGG_CSV):
    with open(AGG_CSV, "w", newline="") as f:
        csv.writer(f).writerow(["Aggregation Method", "RMSE", "MAE", "R2"])
if not os.path.isfile(OVERHEAD_CSV):
    with open(OVERHEAD_CSV, "w", newline="") as f:
        csv.writer(f).writerow([
            "run_idx", "avg_round_s", "avg_train_s", "avg_explore_s",
            "explore_pct_of_round", "clients", "rounds", "client_fraction"
        ])

for run_idx in range(NUM_RUNS):
    # 1) Load and prepare data
    (X_train, y_train), (X_val, y_val), (X_test, y_test) = load_data()
    train_ds = TensorDataset(X_train, y_train)
    val_ds   = TensorDataset(X_val, y_val)
    test_ds  = TensorDataset(X_test, y_test)

    # 2) Split training data across clients (non-IID via Dirichlet over target bins)
    subsets, _, weightings = split_data_nodes(
        train_ds,
        num_nodes=NUM_CLIENTS,
        alpha=DIRICHLET_ALPHA,
        bins=NUM_BINS,
        seed=42 + run_idx  # vary seed per run (optional)
    )

    # 3) Create final test loader (held-out)
    final_test_loader = create_final_data_test_loader(test_ds)

    # 4) Build per-node loaders & nodes
    nodes = []
    for i in range(NUM_CLIENTS):
        client_train_loader, client_val_loader = create_data_loaders(subsets[i], batch_size=BATCH_SIZE)
        node = Node(
            node_id=i,
            train_loader=client_train_loader,
            test_loader=client_val_loader,           # per-round validation at node level
            weighting=weightings[i],
            aggregation_methodology="balance_average"  # will be set dynamically
        )
        nodes.append(node)

    winners = []
    round_times, train_times, explore_times = [], [], []

    # 5) Training + aggregation rounds (scaled)
    for round_idx in range(NUM_GLOBAL_ROUNDS):
        print(f"\n=== Round {round_idx+1}/{NUM_GLOBAL_ROUNDS} ===")
        t_round0 = time.perf_counter()

        # ---- client sampling (scale realism without huge runtime) ----
        m = max(1, int(CLIENT_FRACTION * NUM_CLIENTS))
        selected_ids = np.random.choice(np.arange(NUM_CLIENTS), size=m, replace=False).tolist()
        selected_nodes = [nodes[i] for i in selected_ids]

        # ---- local training + communication (time this block) ----
        t_train0 = time.perf_counter()
        with concurrent.futures.ThreadPoolExecutor() as executor:
            # Each selected node trains locally, then broadcasts; ALL nodes gather.
            executor.map(train_and_communicate, selected_nodes, [nodes] * len(selected_nodes))
        train_dt = time.perf_counter() - t_train0
        train_times.append(train_dt)

        # ---- exploration vs exploitation ----
        if round_idx < NUM_GLOBAL_ROUNDS / 2:
            # time AP-BMS exploration (multi-merge evaluation)
            t_explore0 = time.perf_counter()
            winner = dynamic_aggregation(selected_nodes)   # returns "size" or "balance"
            explore_dt = time.perf_counter() - t_explore0
            explore_times.append(explore_dt)

            winners.append(winner)
            print("Winners so far:", winners)
        else:
            majority = max(set(winners), key=winners.count) if winners else "balance"
            print("Selected aggregator for remainder:", majority)
            for n in nodes:
                n.set_aggregation_methodology("size_average" if majority == "size" else "balance_average")

        # ---- SAFETY: ensure all nodes have packets before aggregation ----
        if not any(n.global_parameters for n in nodes):
            print("No packets this round — rebroadcasting from all nodes.")
            for src in nodes:
                pkt = src.broadcast_parameters()
                for dst in nodes:
                    dst.gather_parameters(pkt)
        else:
            donor = next((m for m in nodes if m.global_parameters), None)
            if donor:
                for n in nodes:
                    if not n.global_parameters:
                        n.global_parameters = donor.global_parameters[:]  # shallow copy

        print("Packet counts per node:", [len(n.global_parameters) for n in nodes])

        # ---- aggregation phase (apply averaged params + epoch tick) ----
        for n in nodes:
            n.aggregate_parameters()
            n.update_epoch()

        # ---- round timing ----
        round_dt = time.perf_counter() - t_round0
        round_times.append(round_dt)
        print(
            f"Round wall-clock: {round_dt:.2f}s | train: {train_dt:.2f}s | explore: {explore_times[-1]:.2f}s"
            if explore_times else
            f"Round wall-clock: {round_dt:.2f}s | train: {train_dt:.2f}s"
        )

    # 6) Final evaluation on the held-out test set (use node 0's model)
    node0 = nodes[0]
    rmse, mae, r2 = evaluate(node0.get_model(), final_test_loader)

    # Decide what to log as the aggregation label
    final_agg = max(set(winners), key=winners.count) if winners else "balance"
    write_metrics_to_csv(AGG_CSV, [final_agg, f"{rmse:.4f}", f"{mae:.4f}", f"{r2:.4f}"])

    # 7) Overhead summary for this run (for the reviewer’s table)
    avg_round = float(np.mean(round_times)) if round_times else 0.0
    avg_train = float(np.mean(train_times)) if train_times else 0.0
    avg_explore = float(np.mean(explore_times)) if explore_times else 0.0
    explore_pct = (avg_explore / avg_round * 100.0) if avg_round > 0 else 0.0

    with open(OVERHEAD_CSV, "a", newline="") as f:
        csv.writer(f).writerow([
            run_idx, f"{avg_round:.4f}", f"{avg_train:.4f}", f"{avg_explore:.4f}", f"{explore_pct:.1f}",
            NUM_CLIENTS, NUM_GLOBAL_ROUNDS, CLIENT_FRACTION
        ])

    print(f"[Run {run_idx}] Test RMSE={rmse:.4f}, MAE={mae:.4f}, R2={r2:.4f} | "
          f"avg_round={avg_round:.2f}s, avg_explore={avg_explore:.2f}s ({explore_pct:.1f}%)")