# -*- coding: utf-8 -*-
"""SWARM_CaliforniaHousing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddxB40kO8BGEpcC9f0jZmzLhISpy5QRJ
"""

import torch
import numpy as np
import pandas as pd
from torchvision import datasets, transforms
import sklearn
from torch.utils.data import DataLoader, random_split, ConcatDataset, Subset, TensorDataset
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import os
from google.colab import drive
import concurrent.futures
import time
import random
import csv

# Mount Google Drive for persistent storage
drive.mount('/content/drive')

# === Configuration (Baseline Regression Swarm) ===
NUM_CLIENTS = 32             # same as NUM_NODES — tens of clients for realism
NUM_GLOBAL_ROUNDS = 15       # same number of global epochs as dynamic version
NUM_LOCAL_EPOCHS = 5         # fewer local epochs per round to keep runtime reasonable
CLIENT_FRACTION = 0.25       # same client sampling ratio per round

BATCH_SIZE = 128             # larger batch for tabular data
LEARNING_RATE = 5e-4         # consistent with dynamic experiment
DIRICHLET_ALPHA = 0.5        # non-IID distribution strength
NUM_BINS = 10                # for Dirichlet-based regression splits

# Device setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

def load_data(normalize=True, seed=42):
    """
    Load and preprocess the California Housing dataset for regression.
    Mirrors the MNIST loader structure for consistency.
    """
    from sklearn.datasets import fetch_california_housing
    import numpy as np
    import torch

    # Load dataset
    data = fetch_california_housing()
    X = data.data.astype(np.float32)
    y = data.target.astype(np.float32).reshape(-1, 1)

    # Normalize features
    if normalize:
        X = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-8)

    # Split into train/test sets (80/20 split)
    n = X.shape[0]
    rng = np.random.RandomState(seed)
    idx = rng.permutation(n)
    n_train = int(0.8 * n)
    train_idx, test_idx = idx[:n_train], idx[n_train:]

    # Create torch tensors
    X_train = torch.tensor(X[train_idx])
    y_train = torch.tensor(y[train_idx])
    X_test = torch.tensor(X[test_idx])
    y_test = torch.tensor(y[test_idx])

    print("California Housing data has been loaded.")
    return (X_train, y_train), (X_test, y_test)

def split_data_nodes(dataset, num_nodes, alpha=0.5, bins=10, seed=42):
    """
    Non-IID partitioning for regression:
    - Assumes `dataset` is a TensorDataset where the 2nd tensor is the continuous target (shape [N,1] or [N]).
    - Discretizes targets into `bins` bins, then applies a Dirichlet(alpha) split per bin across clients.
    - Returns list of Subset(dataset, indices) per client + original dataset + size weightings.
    """
    import numpy as np
    import torch
    from torch.utils.data import Subset

    assert hasattr(dataset, "tensors") and len(dataset.tensors) >= 2, \
        "Expected a TensorDataset with features and targets in dataset.tensors"

    # Extract continuous targets and bin them to create label-like groups
    y = dataset.tensors[1].detach().cpu().numpy().reshape(-1)
    # rng = np.random.RandomState(seed)
    rng = np.random.default_rng()

    # Build bin ids over the continuous target
    edges = np.linspace(y.min(), y.max(), bins + 1)
    bin_ids = np.digitize(y, edges) - 1
    bin_ids = np.clip(bin_ids, 0, bins - 1)

    # Dirichlet split per bin
    client_indices = [[] for _ in range(num_nodes)]
    for c in range(bins):
        idx_c = np.where(bin_ids == c)[0]
        if idx_c.size == 0:
            continue
        rng.shuffle(idx_c)
        props = rng.dirichlet([alpha] * num_nodes)
        # turn proportions into index boundaries
        cuts = (np.cumsum(props) * len(idx_c)).astype(int)[:-1]
        parts = np.split(idx_c, cuts)
        for i, part in enumerate(parts):
            client_indices[i].extend(part.tolist())

    # Shuffle within each client split for good measure
    for lst in client_indices:
        rng.shuffle(lst)

    # Build Subset objects per client
    dataset_splits = [Subset(dataset, inds) for inds in client_indices]

    # Compute weightings for aggregators that use client size
    total = sum(len(s) for s in dataset_splits)
    weightings = [len(s) / total if total > 0 else 0.0 for s in dataset_splits]

    # Logging
    print(f"Data has been split into {num_nodes} clients (Dirichlet alpha={alpha}, bins={bins}, seed={seed})")
    for i, subset in enumerate(dataset_splits):
        print(f"  Size of client {i+1}: {len(subset)}")

    return dataset_splits, dataset, weightings

def create_data_loaders(subset, batch_size=BATCH_SIZE, num_workers=0):
    """
    Create train and validation DataLoaders for a regression subset.
    Mirrors MNIST structure but uses tabular regression data.
    """
    # Split subset into train/validation (80/20)
    val_size = int(0.2 * len(subset))
    train_size = len(subset) - val_size
    train_subset, val_subset = torch.utils.data.random_split(subset, [train_size, val_size])

    # Create DataLoaders
    train_loader = torch.utils.data.DataLoader(train_subset, batch_size=batch_size, shuffle=True, num_workers=num_workers)
    val_loader   = torch.utils.data.DataLoader(val_subset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

    print(f"Data loaders created: {train_size} training samples, {val_size} validation samples.")
    return train_loader, val_loader

# 3. Define the Neural Network Model for Regression
class SimpleNN(nn.Module):
    def __init__(self, input_dim=8, hidden_dim=128):
        """
        Simple two-layer MLP for regression on tabular data (California Housing).
        input_dim = number of features (8 for California Housing)
        """
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)  # Input → hidden
        self.fc2 = nn.Linear(hidden_dim, 1)          # Hidden → output (single continuous value)

    def forward(self, x):
        x = torch.relu(self.fc1(x))   # Hidden layer with ReLU activation
        x = self.fc2(x)               # Output layer (no activation for regression)
        return x

def create_final_data_test_loader(final_testing, batch_size=BATCH_SIZE):
    """
    Create a DataLoader for the final held-out test dataset (regression).
    """
    final_model_test_loader = torch.utils.data.DataLoader(final_testing, batch_size=batch_size, shuffle=False)
    print(f"Final test DataLoader created with {len(final_testing)} samples.")
    return final_model_test_loader

def model_parameters_to_string(model, limit=5):
    """
    Convert model parameters to a readable string (truncated for brevity).
    Works for regression and classification models alike.

    Parameters:
        model: nn.Module
        limit (int): number of parameter values to show per tensor
    """
    params_str = "Model Parameters:\n"
    for name, param in model.named_parameters():
        params_str += f"Name: {name}, Shape: {tuple(param.shape)}\n"
        # Show only a few values per tensor to avoid massive printouts
        flat = param.data.view(-1)
        shown = flat[:limit].tolist()
        params_str += f"Sample values: {shown}"
        if flat.numel() > limit:
            params_str += " ...\n"
        else:
            params_str += "\n"
        params_str += "-" * 50 + "\n"
    return params_str

## NODES PARAMS[0] == balance_score, weighting, rmse

class Node:
    def __init__(self, node_id, train_loader: DataLoader, test_loader: DataLoader, weighting, aggregation_methodology):
        """
        Node for Regression (California Housing)
        Mirrors the MNIST Node structure but uses regression logic.
        """
        self.__train_loader = train_loader
        self.test_loader = test_loader
        self.node_id = node_id
        self.global_parameters = []
        self.model = SimpleNN(input_dim=8)
        self.criterion = nn.MSELoss()
        self.optimizer = optim.Adam(self.model.parameters(), lr=LEARNING_RATE)

        self.weighting = weighting
        self.aggregation_methodology = aggregation_methodology
        self.balance_score = self.get_balance_score()
        self.current_rmse = None
        self.rmse_scores = []
        self.mae_scores = []
        self.r2_scores = []

    # ----------------------------------------------------
    def get_model(self):
        return self.model

    def get_balance_score(self):
        """
        Compute balance score based on evenness of target distribution.
        """
        all_targets = []
        for _, y in self.__train_loader:
            all_targets.extend(y.numpy().flatten())
        if len(all_targets) == 0:
            return 0.0
        hist, _ = np.histogram(all_targets, bins=10, density=True)
        hist = hist / np.sum(hist)
        score = 1 - np.std(hist)
        return float(score)

    # ----------------------------------------------------
    def broadcast_parameters(self):
        """
        Return packet of parameters: [balance_score, weighting, current_rmse, params...]
        """
        packet = [self.balance_score, self.weighting, self.current_rmse or 0.0]
        for p in self.model.parameters():
            packet.append(p.clone())
        return packet

    def gather_parameters(self, params):
        print(f"Gathered Parameters for Node {self.node_id}")
        self.global_parameters.append(params)
        print(f"Length of Gathered Parameters for Node {self.node_id}: {len(self.global_parameters)}")

    # ----------------------------------------------------
    def average_parameters(self):
        if not self.global_parameters:
            raise RuntimeError("No gathered parameters.")
        pkts = [p[:] for p in self.global_parameters]
        template = pkts[0][3:]
        averaged = [torch.zeros_like(p) for p in template]
        for pkt in pkts:
            for i, t in enumerate(pkt[3:]):
                averaged[i] += t
        n = len(pkts)
        averaged = [a / n for a in averaged]
        return averaged

    def size_average_parameters(self):
        if not self.global_parameters:
            raise RuntimeError("No gathered parameters.")
        pkts = [p[:] for p in self.global_parameters]
        weights = [p[1] for p in pkts]
        total_w = sum(weights)
        template = pkts[0][3:]
        averaged = [torch.zeros_like(p) for p in template]
        for pkt, w in zip(pkts, weights):
            for i, t in enumerate(pkt[3:]):
                averaged[i] += t * w
        if total_w > 0:
            averaged = [a / total_w for a in averaged]
        return averaged

    def balance_average_parameters(self):
        if not self.global_parameters:
            raise RuntimeError("No gathered parameters.")
        pkts = [p[:] for p in self.global_parameters]
        balances = [p[0] for p in pkts]
        total_b = sum(balances)
        template = pkts[0][3:]
        averaged = [torch.zeros_like(p) for p in template]
        for pkt, b in zip(pkts, balances):
            for i, t in enumerate(pkt[3:]):
                averaged[i] += t * b
        if total_b > 0:
            averaged = [a / total_b for a in averaged]
        return averaged

    # ----------------------------------------------------
    def aggregate_parameters(self):
        if self.aggregation_methodology == "average":
            averaged_params = self.average_parameters()
        elif self.aggregation_methodology == "size_average":
            averaged_params = self.size_average_parameters()
        elif self.aggregation_methodology == "balance_average":
            averaged_params = self.balance_average_parameters()
        else:
            raise ValueError(f"Invalid aggregation method: {self.aggregation_methodology}")
        self.set_parameters(averaged_params)
        self.global_parameters = []

    def set_parameters(self, parameters):
        new_state = dict(zip(self.model.state_dict().keys(), parameters))
        self.model.load_state_dict(new_state)
        print(f"Set parameters for Node {self.node_id}")

    # ----------------------------------------------------
    def train(self):
        """
        Local training for NUM_LOCAL_EPOCHS.
        """
        self.model.train()
        for epoch in range(NUM_LOCAL_EPOCHS):
            total_loss = 0.0
            for X, y in self.__train_loader:
                self.optimizer.zero_grad()
                preds = self.model(X)
                loss = self.criterion(preds, y)
                loss.backward()
                self.optimizer.step()
                total_loss += loss.item()
            print(f"Node {self.node_id} | Epoch {epoch+1}/{NUM_LOCAL_EPOCHS} | Loss: {total_loss/len(self.__train_loader):.4f}")

        # Update RMSE after local training
        rmse, _, _ = evaluate(self.model, self.test_loader)
        self.current_rmse = rmse

    def evaluate(self):
        """
        Evaluate model on this node's test loader and record RMSE, MAE, R2.
        """
        self.model.eval()
        preds, actuals = [], []
        with torch.no_grad():
            for X, y in self.test_loader:
                out = self.model(X)
                preds.extend(out.cpu().numpy().flatten())
                actuals.extend(y.cpu().numpy().flatten())
        preds = np.array(preds)
        actuals = np.array(actuals)
        mse = np.mean((preds - actuals) ** 2)
        mae = np.mean(np.abs(preds - actuals))
        rmse = np.sqrt(mse)
        r2 = 1 - np.sum((preds - actuals) ** 2) / np.sum((actuals - np.mean(actuals)) ** 2)
        self.rmse_scores.append(rmse)
        self.mae_scores.append(mae)
        self.r2_scores.append(r2)
        self.current_rmse = rmse
        print(f"Node {self.node_id} | RMSE: {rmse:.3f}, MAE: {mae:.3f}, R2: {r2:.3f}")
        return rmse, mae, r2

def train_and_communicate(node, all_nodes):
    """
    Local training for one node, then broadcast its parameters so that
    ALL nodes (including self) gather them for aggregation.
    Works for both baseline and dynamic runs.
    """
    # Local update (updates node.current_rmse internally)
    node.train()

    # Optional: explicit evaluation log (RMSE/MAE/R2)
    rmse, mae, r2 = node.evaluate()
    print(f"Node {node.get_node_id()} metrics — RMSE: {rmse:.4f}, MAE: {mae:.4f}, R2: {r2:.4f}")

    # Broadcast my params; everyone gathers (keeps aggregation safe)
    packet = node.broadcast_parameters()
    for peer in all_nodes:
        peer.gather_parameters(packet)

def evaluate(model, test_loader):
    """
    Evaluate a regression model on a given DataLoader.
    Returns: RMSE, MAE, R2
    """
    model.eval()  # Set model to evaluation mode
    all_targets = []
    all_predictions = []

    with torch.no_grad():
        for features, targets in test_loader:
            outputs = model(features)
            all_targets.extend(targets.cpu().numpy().flatten())
            all_predictions.extend(outputs.cpu().numpy().flatten())

    all_targets = np.array(all_targets)
    all_predictions = np.array(all_predictions)

    # Regression metrics
    mse = np.mean((all_predictions - all_targets) ** 2)
    mae = np.mean(np.abs(all_predictions - all_targets))
    rmse = np.sqrt(mse)
    r2 = 1 - np.sum((all_predictions - all_targets) ** 2) / np.sum((all_targets - np.mean(all_targets)) ** 2)

    return rmse, mae, r2

# Function to write regression metrics to a CSV file
def write_metrics_to_csv(filename, metrics_list):
    """
    metrics_list = [aggregation_method, RMSE, MAE, R2]
    """
    file_exists = os.path.isfile(filename)

    with open(filename, mode='a', newline='') as file:
        writer = csv.writer(file)

        # Write header only when the file is created
        if not file_exists:
            writer.writerow(['Aggregation Method', 'RMSE', 'MAE', 'R2'])

        # Write the data
        writer.writerow(metrics_list)

    print(f"Regression metrics written to {filename}")

import os
import csv
import time
import numpy as np
from torch.utils.data import TensorDataset
import concurrent.futures

aggregation_methodologies = [
    'average',
    # 'size_average',
    # 'balance_average'  # regression uses these; accuracy-based methods removed
]

# === Metrics CSV for performance (already in your code) ===
METRICS_CSV = '/content/drive/My Drive/Swarm_Learning/CaliforniaHousing_Baselinev2.csv'
if not os.path.isfile(METRICS_CSV):
    with open(METRICS_CSV, "w", newline="") as f:
        csv.writer(f).writerow(["Aggregation Method", "RMSE", "MAE", "R2"])

# === Overhead CSV for timing (baseline, avg only) ===
OVERHEAD_CSV = '/content/drive/My Drive/Swarm_Learning/CaliforniaHousing_Baseline_overheadv2.csv'
if not os.path.isfile(OVERHEAD_CSV):
    with open(OVERHEAD_CSV, "w", newline="") as f:
        csv.writer(f).writerow([
            "run_idx",
            "aggregation_method",
            "avg_round_s",
            "avg_train_s",
            "avg_agg_s",
            "agg_pct_of_round",
            "clients",
            "rounds",
            "client_fraction",
        ])

for run_idx in range(30):
    for aggregation_methodology in aggregation_methodologies:
        print(f"\nRun {run_idx+1} | Aggregation Methodology: {aggregation_methodology}")

        # 1) Load dataset
        (X_train, y_train), (X_test, y_test) = load_data()
        train_ds = TensorDataset(X_train, y_train)
        test_ds  = TensorDataset(X_test, y_test)

        # 2) Split into node subsets
        subsets, _, weightings = split_data_nodes(
            train_ds,
            NUM_CLIENTS,
            alpha=DIRICHLET_ALPHA,
            bins=NUM_BINS,
            seed=42 + run_idx
        )

        # 3) Create final test DataLoader
        final_test_loader = create_final_data_test_loader(test_ds)

        # 4) Initialize nodes
        nodes = []
        for i in range(NUM_CLIENTS):
            train_loader, val_loader = create_data_loaders(subsets[i])
            node = Node(
                i,
                train_loader,
                val_loader,
                weightings[i],
                aggregation_methodology
            )
            nodes.append(node)

        round_times, train_times, agg_times = [], [], []

        # 5) Training & aggregation
        for round_idx in range(NUM_GLOBAL_ROUNDS):
            print(f"  Round {round_idx+1}/{NUM_GLOBAL_ROUNDS}")
            t_round0 = time.perf_counter()

            # ---- Local training + communication ----
            t_train0 = time.perf_counter()
            with concurrent.futures.ThreadPoolExecutor() as executor:
                # Each node trains locally and broadcasts; all nodes gather
                executor.map(train_and_communicate, nodes, [nodes] * len(nodes))
            train_dt = time.perf_counter() - t_train0
            train_times.append(train_dt)

            # ---- Aggregation phase (with safety) ----
            t_agg0 = time.perf_counter()

            # SAFETY: ensure all nodes have packets before aggregation
            if not any(n.global_parameters for n in nodes):
                print("    No packets this round — rebroadcasting from all nodes.")
                for src in nodes:
                    pkt = src.broadcast_parameters()
                    for dst in nodes:
                        dst.gather_parameters(pkt)
            else:
                # At least one node has packets; copy to any empty node
                donor = next((m for m in nodes if m.global_parameters), None)
                if donor:
                    for n in nodes:
                        if not n.global_parameters:
                            n.global_parameters = donor.global_parameters[:]  # shallow copy

            # Now it's safe to aggregate on every node
            for n in nodes:
                n.aggregate_parameters()

            agg_dt = time.perf_counter() - t_agg0
            agg_times.append(agg_dt)

            # ---- Round timing summary ----
            round_dt = time.perf_counter() - t_round0
            round_times.append(round_dt)
            print(f"    Round time={round_dt:.2f}s | train={train_dt:.2f}s | agg={agg_dt:.2f}s")

        # 6) Evaluate final global model (take node 0)
        node0 = nodes[0]
        rmse, mae, r2 = evaluate(node0.get_model(), final_test_loader)

        # Write metrics to CSV
        metrics_list = [aggregation_methodology, f"{rmse:.4f}", f"{mae:.4f}", f"{r2:.4f}"]
        write_metrics_to_csv(METRICS_CSV, metrics_list)

        # 7) Overhead summary (baseline, like dynamic version)
        avg_round = float(np.mean(round_times)) if round_times else 0.0
        avg_train = float(np.mean(train_times)) if train_times else 0.0
        avg_agg   = float(np.mean(agg_times)) if agg_times else 0.0
        agg_pct   = (avg_agg / avg_round * 100.0) if avg_round > 0 else 0.0

        # Append overhead row to CSV
        with open(OVERHEAD_CSV, "a", newline="") as f:
            csv.writer(f).writerow([
                run_idx,
                aggregation_methodology,
                f"{avg_round:.4f}",
                f"{avg_train:.4f}",
                f"{avg_agg:.4f}",
                f"{agg_pct:.1f}",
                NUM_CLIENTS,
                NUM_GLOBAL_ROUNDS,
                CLIENT_FRACTION,
            ])

        print(
            f"  {aggregation_methodology} → RMSE={rmse:.4f}, MAE={mae:.4f}, R2={r2:.4f} | "
            f"avg_round={avg_round:.2f}s, avg_agg={avg_agg:.4f}s ({agg_pct:.1f}% of round)"
        )

